name: Run python scripts
description: Runs the Python code in all of the files in the given directory in Deephaven
inputs:
  directory:
    description: The path to the directory to run the code
    required: true
  host:
    description: The host name or IP address of the Deephaven instance
    required: true
  port:
    description: The port to access on the host
    required: true
  max-retries:
    description: The maximum attempts to retry connecting to Deephaven
    required: false
    default: 5
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup environment
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
        find . -name "*.py"
      shell: sh
    - name: Run python script
      run: python ${{ github.action_path }}/script.py ${{ inputs.directory }} ${{ inputs.host }} ${{ inputs.port }} ${{ inputs.max-retries }}
      shell: sh
