name: PR check

on:
  pull_request:
    branches:
      - main

jobs:
  pr_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          curl https://raw.githubusercontent.com/deephaven/deephaven-core/main/containers/examples/base/docker-compose.yml > ./test/docker-compose.yml
          docker-compose -f ./test/docker-compose.yml up -d
      - name: Run PR check
        uses: ./.
        with:
          directory: ${{ github.action_path }}/test
          host: localhost
          port: 10000
      - name: Assert tables present
        uses: deephaven/action-assert-dh-tables-present@main
        with:
          table-names: result0,result1,result2,result3,result4
          host: localhost
